# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-24 05:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_blogger'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blogger',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='bloggers', to='dashboard.Blogger'),
            preserve_default=False,
        ),
    ]
