# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-24 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_post_blogger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('post', models.ManyToManyField(related_name='comments', to='dashboard.Post')),
            ],
        ),
    ]
