# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-24 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20190624_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post',
            field=models.ManyToManyField(related_name='comments', to='dashboard.Comment'),
        ),
    ]
