# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-24 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_post_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='comment',
        ),
    ]
